### ISSUE TITLE
Add simple AES encryption

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/ioBroker.hiob#13]
Add simple AES encryption

**Comment by Lucky-ESA** [comment]
https://github.com/moba15/ioBroker.hiob/pull/14

**Comment by Lucky-ESA** [comment]
@santa81
Hast du auch wirklich die aktuelle Version 0.1.2 installiert?

**Comment by santa81** [comment]
@Lucky-ESA hi, ja eben gerade neu installiert. Habe dir auch über discord geschrieben, dort kann ich ggf schneller antworten.

**Comment by moba15** [comment]
Stelle ansonsten noch mal sicher, dass du beim Adapter unter deinem device aes_active auf true stehen hast. 
Falls ja generiere dir doch nochmal ein neuen aes_key und lass ihn dir anzeigen und füge ihn in der App hinzu. 
So konnte ich (warum auch immer) mein Fehler vorhin beheben

**Comment by santa81** [comment]
@Lucky-ESA @moba15 
Fehler gefunden. Habe mir die Doku nicht angesehen und nach meiner Meinung intuitiv bedient.
hatte den datenpunkt view aes key nicht gesehen und habe somit den langen "schlüssel" kopiert.
Mit den vorherigen Versionen hatte dies geklappt.  Jetzt habe ich mir den Schlüssel anzeigen lassen und kopiert. 
schon lief die app wieder.

sorry, hätte mir das genauer ansehen sollen.

**Comment by Lucky-ESA** [comment]
Freut mich, sorry das ich das so machen muss aber sensible Daten dürfen in iobroker nicht dauerhaft sichbar sein.
