### ISSUE TITLE
Preperation for latest request

### ISSUE THREAD

**Issue by moba15** [moba15/ioBroker.hiob#15]

**Comment by Lucky-ESA** [comment]
[Prettier hinzugefügt aber nicht aktiviert](https://github.com/moba15/ioBroker.hiob/pull/17/commits/afd0790f3b5ac5fc82ac9aa020d621c9d6ba1834)
[Anlegen von Datenpunkten nur 1 x nach Adapter Neustart](https://github.com/moba15/ioBroker.hiob/pull/17/commits/aba7cf6dc8b4a3fbb8057f2781af35a93b78ff42)
[Reduzierung von Objektabfragen](https://github.com/moba15/ioBroker.hiob/pull/17/commits/c404082f4b2eb84576ae8f2e22422c03bc20ddef)
[Reduzierung GET Abfragen](https://github.com/moba15/ioBroker.hiob/pull/17/commits/598583e893c457660b4ace0a97ef5abf897c3472)
[Counter Part](https://github.com/moba15/ioBroker.hiob/pull/17/commits/56892902c0c77c9c170fb791086f1f3ce29a1d2c) von [Pull Request](https://github.com/moba15/hiob_app/commit/3087875bf627e342ef89d231fb43d86e29f39a44) Alle Datenpunkte als eine Antwort bei sync und Neuverbindung

**Comment by Lucky-ESA** [comment]
Leider hast du diesen [commit](https://github.com/moba15/ioBroker.hiob/pull/31/commits/fec92e6c054431a22c8f493eadb29e4cfc339301) nicht übernommen. Die auch bitte unter "About" eintragen
Bitte dann noch im Ordner ioBroker.hiob npm update --save-dev und npm update --save ausführen

👀 [W170] "common.keywords" should not contain "iobroker, adapter, smart home" [io-package.json](https://github.com/moba15/ioBroker.hiob/blob/master/io-package.json)
👀 [W173] "@iobroker/adapter-core" (^3.0.4) should be 3.0.6 or newer - please update

In der readme.md aus Node 16 eine 18 machen.

Wenn du keine Zeit hast kann ich das auch machen.

**Comment by moba15** [comment]
Ok seltsam, warum der nicht übernommen wurde. Pass ich an!

**Comment by Lucky-ESA** [comment]
OK, super. Soll ich für Device ein PR erstellen? Habe es schon im Fork. Aber die Prüfung der DP sollte nur beim Ersten connected geprüft werden und nicht bei jeder Verbindung.
[Commit](https://github.com/Lucky-ESA/ioBroker.hiob/commit/05c42014ca0d4931095e1b43b7d77516644b6085)

**Comment by moba15** [comment]
Wie hast du das mit den Devices gelöst

**Comment by moba15** [comment]
Aber du kannst ja mal ein PR erstellen und dann kann ich schauen ob das so ist wie ich es mir vorgestellt habe.

**Comment by Lucky-ESA** [comment]
Das Problem ist, das der Ordner "devices" keinen type oder Namen hat. Daher kann dieser Ordner in ioBroker nicht editiert werden. Da einige Beta Tester nun einen devices Folder ohne type haben, muss die Funktion setObjectAsync dieses korrigieren. Sobald du auf latest bist, sollten diese beiden markieren Funktionen gelöscht werden.

**Comment by Lucky-ESA** [comment]
Kannst du bitte in der tsconfig.json das ändern:
`"extends": "@tsconfig/node16/tsconfig.json",`

in

`"extends": "@tsconfig/node18/tsconfig.json",`

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Please check W170 - Ignorieren da der Check schon 1 Woche alt ist und du mein PR bereits übernommen hast. Kannst du bitte noch die Keywords aug GIT noch unter "About" eintragen

Readme.me sollte kein Problem sein

Data Point: Kann ich Sonntag korrigieren

io-package: "js-controller": ">=3.3.22" -> "js-controller": ">=5.0.0"

dependabot: [Siehe bei mir](https://github.com/Lucky-ESA/ioBroker.imap/blob/master/.github/dependabot.yml)
Für auto merge: [Optional](https://github.com/Lucky-ESA/ioBroker.imap/blob/master/.github/workflows/dependabot-auto-merge.yml)

Gruß//Lucky

**Comment by moba15** [comment]
Danke, hatte über das Wochenende keine Zeit. Werde es mir morgen nochmal genauer anschauen und auch dann einen neuen Release erstellen

**Comment by Lucky-ESA** [comment]
Kein Stress. Bei diesen Änderungen muss du kein neues Release erstellen.
Du musst lediglich mcm1957 antworten das alles erledigt ist. Muss noch gestehen das ich deine notification.md nicht richtig gelesen hatte. Wenn du was bei description hinzufügst dann niemals persönlich ansprechen. Benutze zum Bsp. als du einfach man...Du kannst dann blablabla in Man kann blablabla.

**Comment by moba15** [comment]
dependabot ist wenn ich es richtig verstanden habe auch optional oder? 
Also ich werde es irgendwann mal einrichten, sobald ich die zeit dafür finde. Kann nur noch etwas dauern

**Comment by Lucky-ESA** [comment]
Die dependaboit.yml wird eher gerne gesehen aber der auto-merge ist optional. Es ist auch immer zu prüfen, ob irgendweine Funktion ersetzt wurde oder neue Attribute hat. Am Wochenende erstelle ich ein PR für die RAM Darstellung, da kann ich auch die Datei noch hinzufügen. Für auto-merge musst du über GIT einen Key erstellen und diesen in den Settings hinzufügen.

**Comment by moba15** [comment]
Hab dependabot jetzt mal aktiviert. Auto merge werde ich mir noch anschauen

**Comment by Lucky-ESA** [comment]
Habe bei mir automerge aktiviert, vergesse es immer und aktualisiere mit dev-server. Dann habe ich immer mit Konflikte zu kämpfen...Das hat Vorteile aber auch Nachteile.
Kannst du bitte noch in der Readme das ändern.
Data points can be controlled with the HioB APP.
in
States can be controlled with the HioB APP.

Dann bleibt bei mir nun nur noch 1 Punkt ungeklärt. In der src/lib/adapter-config.d.ts haben bei Javascript Adapter die Configs nichts verloren. Keine Ahnung ob das bei Typescript auch so ist...Hast du diese geändert?
So sieht meine aus:
[config](https://github.com/Lucky-ESA/ioBroker.imap/blob/master/lib/adapter-config.d.ts)

Gruß//Lucky

**Comment by moba15** [comment]
Danke für den Hinweis. 
Meine config sieht ähnlich aus. ich kann sie natürlich auch direkt in den src ordner verschieben, wenn du das damit meinst

**Comment by Lucky-ESA** [comment]
Musst du nicht ändern. Wir warten jetzt mal ab was apollon77 sagt.
Eigentlich sollten nun alle auf 0.1.3 gewechselt haben, sodass jetzt bald die 2 Stellen mit setObjectAsync gelöscht werden können. Wenn du später mal was in den Objekten ändern muss, kannst du dir eine Hilfsfunktion bauen. Du kannst dir ja anschauen wie wir das bei dem [Worx Function cleanOldVersion](https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/main.js) machen. Hier muss ich beim nächsten Release einige alte Ordner löschen :-)

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
apollon77 hat ja gestern geantwortet.
1. Hab ich ja oben beschrieben. Es ist somit Zeit diese 2 Stellen zu entfernen
2. Ist optional
3. Wird  doch nicht benötigt daher löschen
4. Verstehe die Frage nicht

**Comment by Lucky-ESA** [comment]
OK, habe es leider doch richtig verstanden. Sollte in der Enum Hiob mehr als 100 States eingetragen sein (besser wäre 50), dann sollen wir lieber alle Adapter, von den States in Enum stehen, komplett subscriben. Habe da eine kleine Lawine losgetreten da nun einige Adapeter überarbeitet werden müssen...Lass uns mal überlegen wie das umzusetzen ist.

**Comment by Lucky-ESA** [comment]
Bitte Punkt 3 nicht umsetzen. Das ist eher besser als alles einzeln...

**Comment by Lucky-ESA** [comment]
1. Hab ich ja oben beschrieben. Es ist somit Zeit diese 2 Stellen zu entfernen
2. Ist optional
3. Kannst du lassen und dafür alle anderen (6 x) subscribeStatesAsync löschen (main.js und loginmangaer.js)
4. Wenn mehr als 100 subscribts benötigt werden muss der Adapter wechseln auf Bsp. subscribeForeignStates("hm-rpc.0.*) und die Änderungen in der onStateChange abfangen

Soll ich das mal umsetzen und dir einen PR senden. Kannst es dir anschauen und dann das selber bei dir umsetzen und den PR einfach schließen.

Gruß//Lucky

**Comment by moba15** [comment]
Hey, gerne kannst du das mal umsetzen. Ich bin dieses Wochenende leider nur Gesundheitsbedingt verhindert, komm also erst Ende nächster Woche dazu mir das genauer anzuschauen. Soweit ich das sehen kann, sollte das aber möglich sein umzusetzen.

**Comment by moba15** [comment]
Also Punkt 4 sollte eigentlich kein Problem sein, wenn man sich die bereits Abonnierten einfach merkt. Evtl sogar einfach in einer hashmap, wobei der key der Adapter name plus dessen Instanz Nummer ist. So sollte man recht schnell feststellen können, ob es mehr als 50 sind. Ich stell mir nur die Frage, wenn ich zuerst z.B subscribeForeignStates("test.0.test.test) gemacht habe und danach subscribeForeignStates("test.0.*), soltte man dann test.0.test.test wieder unsubscriben?

**Comment by Lucky-ESA** [comment]
Immer unsubscriben. Was mich allerdings stört, dass die Last nun beim Adapter liegt. Verwenden User 10 Adapter und hat mehr als 50 States, dann müsseen alle States der Adapter subscriben. Das könnte dann so 15000 States werden die abgefangen werden müssen. Hier könnte die RAM Last sehr hoch gehen. Besser wäre, wenn die User alias States erstellen und der Adapter dann nur alias.0 subscriben. Das müssen wir dann mal testen und ggf. in der Anleitung eine Empfehlung schreiben.

Gute Besserung

Gruß//Lucky

**Comment by moba15** [comment]
Es gab ja auch mal die Idee, dass man mit aliasen arbeitet anstatt mit enums. Vieleicht wäre das diesbezüglich auch nochmal eine Überlegung wert. Vieleicht auch mit Auswahl Möglichkeit.

**Comment by Lucky-ESA** [comment]
Hatte ich auch noch im Kopf...Hier die Antwort...
xxx, [21.04.2024 11:46]
@Apollon77 Hast du ein Thema damit wenn die benötigen States als alias angelegt werden und wir dann alias.0.* subscriben?

Ingo Fischer, [21.04.2024 11:47]
Willst du User wirklich so limitieren ?

**Comment by Lucky-ESA** [comment]
Als Einstellung in der Instance Settings ob Enum oder alias wäre dann super.

**Comment by moba15** [comment]
Vieleicht könnte das Handy sich alle states unter alias.0 holen, diese dann in eine Datenbank speichern. Dann kann der Nutzer einfach mit passenden filtern (nach Typ, enum oder Funktion) nach den passenden state suchen. Dies müsste man wahrscheinlich nur in einer sql Datenbank machen damit die Performance der App nicht drunter leidet.

**Comment by moba15** [comment]
> Als Einstellung in der Instance Settings ob Enum oder alias wäre dann super.

Ja wäre wahrscheinlich das beste, es wird wahrscheinlich nicht jeder aliase pflegen.

**Comment by moba15** [comment]
> Das müssen wir dann mal testen und ggf. in der Anleitung eine Empfehlung schreiben.

Ich würde es vieleicht aber erstmal so machen. Einfach ab einer gewissen Anzahl  alle States vom Adapter subscriben und dann als Hinweis, dass ab einer gewissen Anzahl von Adaptern mit 50+ States, aliase sinnvoller wären.

**Comment by Lucky-ESA** [comment]
Würde dann so aussehen.
![Screenshot 2024-04-21 150946](https://github.com/moba15/ioBroker.hiob/assets/83980942/97a4f5fb-e2b9-484f-830e-2b954da53fcb)
![Screenshot 2024-04-21 151010](https://github.com/moba15/ioBroker.hiob/assets/83980942/1acb1cc8-71ca-4003-b0aa-85772a92fb31)

**Comment by moba15** [comment]
Ja das sieht nach einer sinnvollen Lösung aus 👍

**Comment by Apollon77** [comment]
Alias is still not used that often by users, solimiting to alias only makes that not better. ALso alias.* subscription could lead to other effects ... we just identified this also as a pitfall and will fix for js-controller 6

**Comment by Lucky-ESA** [comment]
@moba15 Sorry das ich mich jetzt erst melde. Die Aufgabe ist jetzt nicht richtig umgesetzt aber vielleicht habe ich mich auch falsch ausgedrückt. Wenn es mehr als 50 States sind, dann lieber alles suncriben.
Bsp.:
0_userdata.0 -> 10 States
alias.0 -> 10 States
hm-rpc.0 -> 20 States
hm-rpc.1 -> 19 States
hm-rpc.2 -> 1 State

Das wären dann 50 und somit wie folgt zu subscriben:
0_userdata.0 -> alle
alias.0 -> einzeln
hm-rpc.0 -> alle
hm-rpc.1 -> alle
hm-rpc.2 -> alle

Das passiert derzeit nicht. Mit ein wenig Pech hast du dann 10000 States subscribed wovon du nur 50 benötigst.
Ob für diese Anzahl das packages async-mutex richtig ist kann ich nicht beurteilen. Du hast allerdings bereits die States in der valueDatapoints und die kann man zum selektieren super nehmen.

Gruß//Lucky

**Comment by moba15** [comment]
Danke nochmal für deine Rückmeldung. Dann habe ich das tatsächlich falsch verstanden. Sollte jedoch keine große Änderung sein, werde ich die Woche nochmal umsetzen.

**Comment by Lucky-ESA** [comment]
@moba15 Hast du wieder zeitliche Themen? Des weiteren funktioniert das Hinzufügen oder Entfernen von States unter ENUMS nicht.

**Comment by moba15** [comment]
Wenn du mit zeitlichen Themen meinst, ob ich aktuell Zeit habe zum weiterentwickeln: Aktuell bin ich wieder mit Uni und Umzug etwas eingespannt. Ich bin aber trotzdem im Hintergrund weiter am Arbeiten, kleinere Bugs versuche ich schnell zu beheben. Was größere features angeht benötige ich dafür aktuell mehr Zeit. Neue Widgets werde ich vermutlich auch erst wieder hinzufügen, wenn ich mit meinem Refactoring fertig bin: [branch](https://github.com/moba15/hiob_app/tree/refactor/advanced-widget)

Schau ich mir an. Bei mir funktioniert aktuell eigentlich alles.

**Comment by Lucky-ESA** [comment]
Habe wohl dann deine letzte Änderung nicht mitbekommen. Dann vergiss meinen Beitrag...

**Comment by Lucky-ESA** [comment]
Glückwusch, dein Adapter ist nun im latest repo.
Bitte jetzt dir die Rechte für [Tester](https://forum.iobroker.net/category/91/tester) von [Homoran](https://forum.iobroker.net/user/homoran) geben lassen. Er soll auch bitte den [Thread](https://forum.iobroker.net/topic/55250/neuer-adapter-hiob-handy-app) schließen. Nach 2 Wochen erhälst du ein issues von Bluefox. Über den Link kannst du dann ein PR für stable erstellen. Sobald der PR merged wird, löscht sich der isuues automatisch. Es müssen allerdings positive Posts existieren die die einwandfreien Funktionalität bestätigen.

Gruß//Lucky

**Comment by moba15** [comment]
Danke :+1:  
Werde ich dieses Wochenende mal alles machen, danke für den Hinweis.

**Comment by moba15** [comment]
Kurze nachfrage, wieso sollte der aktuelle Thread geschlossen werden? 
Rechte für Tester habe ich bereits

**Comment by Lucky-ESA** [comment]
Da es keinen Sinn macht 2 gleiche Threads offen zu haben. Schliessen und mit einem Link zu tester Thread.

**Comment by Lucky-ESA** [comment]
Du musst bitte ein neues Release 0.1.5 erstellen. Das Release 0.1.4 enthält noch die Blockly Datei die bei Javascript Adapter >= 8.5.0 den Block sendTo unbrauchbar macht.
Dann bitte 2 Wochen später ins stable repo hinzufügen.

Gruß//Lucky

**Comment by moba15** [comment]
Werde ich diese Woche angehen. Hab jetzt wieder ein bisschen mehr Zeit :+1:

**Comment by Lucky-ESA** [comment]
Denke bitte daran den Adapter nun ins stable repo einzutragen. Du kannst das über die Links im Issues durchführen.

**Comment by moba15** [comment]
Wie hier bereits hier [#79] erwähnt, werde ich damit warten bis ich meine Prüfung für dieses Jahr abgeschlossen habe (10.8), damit ich für mögliche Fehler Zeit habe. 
Ab dann hab ich auch wieder Zeit mehr zu programmieren. Hab auch ordentlich motivation neue dinge zu programmieren.

**Comment by Lucky-ESA** [comment]
Ich hoffe das du deine Prüfung erfolgreich abgeschlossen hast. Wirst du jetzt die APP weiterentwickeln?

**Comment by moba15** [comment]
Ja bin aktuell noch dran das template system umzuschreiben. Bin hoffentlich aber demnächst soweit, die erste beta version zu veröffentlichen. Damit sollte es deutlich performanter und vor allem einfacher werden für neue widgets.
Hiermit würde ich dieses Issue schließen :)
