### ISSUE TITLE
Missing updates in the iobroker integrated packet management for hiob adapter

### ISSUE THREAD

**Issue by BerziOnline** [moba15/ioBroker.hiob#19]
**Describe the bug**  
Missing updates in the iobroker integrated packet management for hiob adapter. 
The last version offered there is about 0.0.40 or 0.0.41.
The new Android App of Hiob now needs at least v0.0.60, what could have been better described in the app updates. "Normal" users has no chance to avoid problems, because they cannot know before updating the android update and they won't receive the needed adapter updater in the iobroker.

I would recommend two things:

1. ensure the adapter updates are available in the iobroker adapter mgmt
2. if updates of the mobile app will lead to issues having older versions (because the issue was known before) inform the users in the update description of the app-update

**Comment by BerziOnline** [comment]
I didn't know, how to name it :-) 
Simply said, your version is missing in the frontend of the iobroker adapters:

![2024-03-04_12-17](https://github.com/moba15/ioBroker.hiob/assets/46005508/c1dedfc0-4609-45c9-994a-dd0689a123a2)

**Comment by moba15** [comment]
Currently the adapter is in none of the official ioBroker repositories (hopefully not for long anymore), so you always need to update/install the adapter over CLI npm manually. For now.

**Comment by BerziOnline** [comment]
Oh I see - my fault! I thought my last version has been installed over the iobroker repositories.

Overall it would  be a good idea trying to organize adapter updates over this way :-) 

Thanks a lot!
