### ISSUE TITLE
Organisation von Template & Screens über den Adapter

### ISSUE THREAD

**Issue by BerziOnline** [moba15/ioBroker.hiob#23]
Bei intensiver Nutzung der Smartphone-App benötigt es viel Zeit die verschiedenen Templates anzulegen, Screens zu organisieren, etc.

Es wäre ein unheimlicher Komfortgewinn, wenn man diese Organisation auch zusätzlich am PC im Adapter handhaben könnte.
Es soll nicht die Bearbeitung in der App ersetzen. Aber es wäre ein hilfreiches Upgrade, wenn diese Bearbeitung (synchronisiert) auch am PC innerhalb des Adapters möglich wäre. 

Erstellung/Bearbeitung/Verschieben usw. von Screens und Templates - wie es am Smartphone eben auch möglich ist.

Damit könnte man komplexere Gebilde übersichtlicher und vermutlich effizienter organisieren. Änderungen sollten dann eben als Ergebnis direkte Auswirkungen auf die App bei einem Sync haben - und umgekehrt.

**Comment by moba15** [comment]
Es gibt eine PC version dieser App und über die Einstellungen confic sync kannst du vorgenommene Einstellungen am PC hochladen und am Handy herunterladen. Hier findest du eine kleine Anleitung wie man seine aktuellen Einstellungen hochladen kann: https://github.com/moba15/ioBroker.hiob/blob/main/docs/de/backups.md

**Comment by BerziOnline** [comment]
Ja mega stark! Das war mir nicht bekannt mit der PC-Version. 
Ich sehe, dass du auch ein Linux-Release mit bei hast. Wie lässt sich dieses denn ausführen?

**Comment by moba15** [comment]
Ja ist auch noch nicht so lange her, dass ich da jetzt angefangen habe eine PC version mit zu pflegen. Es sei jedoch dazu gesagt, dass die App immer noch nur für ein Handy gedacht und aufgebaut ist. Somit sollte man jetzt nicht auf die beste PC Erfahrung hoffen.
Du musst die .zip zunächst in irgendeinen Ordner entpacken. Und danach kannst du die smart_home datei ausführen. Entweder mit dopple klick in einem Dateiexplorer oder mit ./smart_home aus der Konsole.

**Comment by BerziOnline** [comment]
Danke dir! Genauso hatte ich es versucht, aber es wirft folgende Fehlermeldung:

> $./smart_home 
> ./smart_home: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./smart_home)

Für welche Distro hast du es denn kompiliert? Ich glaube in diesem Falle fehlt mir eine C-Bibliothek, um es auszuführen.
Getestet habe ich es auf einem Linux Mint.

**Comment by moba15** [comment]
Hast du die anderen Dateien/Ordner im slebem Ordner gespeichert wie die smart_home Datei?

**Comment by BerziOnline** [comment]
Ja. Nachdem das Archiv entpackt ist liegt diet die smart_home Datei ja mit den Ordnern data und lib gemeinsam ab.

**Comment by moba15** [comment]
Ok. Dann wirds vermutlich an einer fehlenden library liegen. Die App wurde auf Ubuntu kompeliert sollte aber auf den Großteil aller x86 Architekturen laufen. Ist auch bereits mit Arch Linux getestet. Bevor ich dir jedoch spekulativ irgendwelche library zur Installation gebe, teste ich es erstmal selber auf einem Mint OS

**Comment by Lucky-ESA** [comment]
Mein Norton löscht 3 Dateien. Hast du vielleicht auch ein Virenprogramm was Dateien löscht?

**Comment by BerziOnline** [comment]
@Lucky-ESA Nee, das ist es leider nicht
@moba15 Die build-essentials sind auch schon drauf gewesen. Nach einer kleinen Recherche bin ich darauf gestoßen, dass eventuell die Linux Mint Version 20.3, die hier im Einsatz ist (ein Upgrade ist aus anderen Gründen nicht möglich) das Problem ist. Soll also vorerst nicht weiter dein Problem sein! :-)

**Comment by moba15** [comment]
Alles klar. Hast du nur vieleicht schomal geschaut ob libc6 installiert ist. Des kann man auch mit apt installieren, hab gerade den Befehl nicht mehr parat.

**Comment by moba15** [comment]
Konntest du den Fehler inzwischen finden?
Wenn nicht könntest du mir nochmal deine MINT version zukommen lassen.

**Comment by BerziOnline** [comment]
Nein, habe den Fehler nicht finden können. Es handelt sich um eine Linux Mint Version 20.3 mit Cinnamon 5.2.7. Aber mach dir wegen mir hier keinen Stress. Ich hatte es bewusst mal liegen gelassen, da ich in den nächsten Wochen ein Upgrade plane, dann kann ich nochmal Feedback geben, ob es danach möglich war.

**Comment by moba15** [comment]
Hey, ich wollte inzwischen mal Nachfragen, ob du es nochmal probiert hast?

**Comment by BerziOnline** [comment]
Tatsächlich werde ich wohl erst über die Weihnachtszeit dazu kommen mein System komplett neu aufzusetzen und gehe davon aus, dass das Problem dadurch behoben sein wird. Würde es deshalb zunächst einmal schließen, da das Problem vermutlich eher OS bezogen ist.
