### ISSUE TITLE
Translation data point name

### ISSUE THREAD

**Issue by Lucky-ESA** [moba15/ioBroker.hiob#25]
Verwendet ein User einen Adapterdatenpunkt von einem gut programmierten Adpter, dann ist der Name ein JSON`s mit 11 Sprachen. In der APP wird dann der JSON angezeigt und manchmal sogar gar nichts.
Bei Enums update sollte auf Object geprüft werden und die eingestellte Sprache übergeben werden.
Bsp. Sprache auslesen:
```
        this.lang = "de";
        const obj = await this.getForeignObjectAsync("system.config");
        if (obj && obj.common && obj.common.language) {
            try {
                this.lang = obj.common.language === this.lang ? this.lang : obj.common.language;
            } catch (e) {
                // Nothing
            }
        }
```

**Comment by moba15** [comment]
Ich stelle mir nur die Frage ob es nicht sinvoller ist die Sprache erst auf der App auszuwählen. Oder ob die bereits am Adapter ausgewählt wird. Mit der ersteren Lösung wäre es möglich Geräte mit verschiedenen Sprachen zu verwenden.

**Comment by Lucky-ESA** [comment]
Die Arbeit solltest du dir sparen. Es ist mir nur per Zufall (auf mein Testsystem) aufgefallen. Die Frage ist, wie viele Adapter gibt es die alle Sprachen anbieten. Hier sollte nur die Sprache von ioBroker geprüft werden. Viele Adapter erzeugen Datenpunkte mit dem Namen der API und daher gibt es keine 11 Sprachen. Mein Gefühl sagt mir, dass es vielleicht 5% an Adapter gibt, die die 11 geforderten Sprachen unterstützen.
