### ISSUE TITLE
Error Export

### ISSUE THREAD

**Issue by Pocky2507** [moba15/ioBroker.hiob#3]
Moin @moba15 
Egal in welchen Ordner ich auf dem Smartphone exportieren möchte, 
kommt ein Error.
[Screenshot_2022-06-06-18-48](https://user-images.githubusercontent.com/22934504/172207679-fee5365f-91e3-450e-aabb-be9659f4781d.jpg)

**Comment by moba15** [comment]
Moin Pocky,
ich schau mir das problem sofort genauer mal an, aber ich hätte noch ein paar fragen.
1. Hat die Hiob App die berechtigung bekommen auf Dateien zuzugreifen?
2. Welche Android version benutzt du momentan?

MfG

**Comment by Pocky2507** [comment]
Im Downloads Ordner das gleiche.
Aber im Download Ordner ging es.

**Comment by moba15** [comment]
Ok danke dir für die Info. Ich teile es mit sobald, ich den Fehler behoben habe.

**Comment by moba15** [comment]
Bei den neueren Android-Version wird eine extra Berechtigung für das Schreiben in externe Ordnern benötigt, mit der normalen Berechtigung ist es der App nur gestattet auf bestimmte Ordner zuzugreifen, um das Sicherheitsrisiko zu minimieren. Deswegen habe ich mich dagegen entschieden, diese extra Berechtigung vom Nutzer anzufragen, jedoch liefert die App (in der neuen Version) eine besser Fehlererklärung.
Genauere info ist z.B. hier zu finden: `https://support.google.com/googleplay/android-developer/answer/10467955?hl=de`
