### ISSUE TITLE
Switch Datapoint

### ISSUE THREAD

**Issue by BassT23** [moba15/ioBroker.hiob#6]
Hi,

der Name des Switch Datapoint sollte besser der "Name" sein, nicht der Datenpunkt.
Zum "Problem";

bei mir wird jetzt fast alles mit "SET" angezeigt. Es ist so sehr schwer herauszufinden welcher SET was ist, ...
Daher besser den Namen verwenden.

Bitte ;)

Vielen Dank

**Comment by moba15** [comment]
Ja vielen Dank für den Hinweis, ist bereits auf der Verbesserungs Liste :)

**Comment by moba15** [comment]
Sollte inzwischen behoben sein!
