### ISSUE TITLE
Endloses Enums Update, wenn Datenpunkt eine Klammer enthält

### ISSUE THREAD

**Issue by BerziOnline** [moba15/ioBroker.hiob#7]
Wenn man im iobroker in den Enums einen Datenpunkt zu den Hiob-Aufzählungen hinzufügt, der im Namen eine Klammer '(' oder ')' trägt, dann führt das dazu, dass das Enums Update in der App unter den iobroker settings unendlich läuft und nicht zum Abschluss kommt.

Die Lösung auf Seiten des users ist es natürlich einfach die Klammer zu vermeiden, jedoch haben einige Datenpunkte von Adaptern standardmäßig solche Sonderzeichen enthalten. Nicht jeder User wird in der Lage sein das darauf zurückzuführen.

**Comment by BerziOnline** [comment]
Ich ergänze:

Die Probleme treten offensichtlich nicht nur auf, wenn die Klammern sich im Namen befinden, sondern auch wenn die Daten selbst welche enthalten.

Oberes Szenario konnte durch Umbenennen (Entfernung der Klammern aus dem Namen) behoben werden.
Das Problem tritt aber bei einer JSON-Tabelle bspw ebenfalls auf.

Beispieldaten der Tabelle:

`[{"Time":"2023-08-28T04:28:55+00:00","Total":"0","PV":"0"},{"Time":"2023-08-28T05:00:00+00:00","Total":"9","PV":"9"},{"Time":"2023-08-28T06:00:00+00:00","Total":"30","PV":"30"},{"Time":"2023-08-28T07:00:00+00:00","Total":"52","PV":"52"},{"Time":"2023-08-28T08:00:00+00:00","Total":"71","PV":"71"},{"Time":"2023-08-28T09:00:00+00:00","Total":"85","PV":"85"},{"Time":"2023-08-28T10:00:00+00:00","Total":"95","PV":"95"},{"Time":"2023-08-28T11:00:00+00:00","Total":"98","PV":"98"},{"Time":"2023-08-28T12:00:00+00:00","Total":"98","PV":"98"},{"Time":"2023-08-28T13:00:00+00:00","Total":"89","PV":"89"},{"Time":"2023-08-28T14:00:00+00:00","Total":"76","PV":"76"},{"Time":"2023-08-28T15:00:00+00:00","Total":"58","PV":"58"},{"Time":"2023-08-28T16:00:00+00:00","Total":"37","PV":"37"},{"Time":"2023-08-28T17:00:00+00:00","Total":"15","PV":"15"},{"Time":"2023-08-28T18:00:00+00:00","Total":"3","PV":"3"},{"Time":"2023-08-28T18:09:06+00:00","Total":"0","PV":"0"},{"Time":"2023-08-29T04:30:19+00:00","Total":"0","PV":"0"},{"Time":"2023-08-29T05:00:00+00:00","Total":"8","PV":"8"},{"Time":"2023-08-29T06:00:00+00:00","Total":"30","PV":"30"},{"Time":"2023-08-29T07:00:00+00:00","Total":"52","PV":"52"},{"Time":"2023-08-29T08:00:00+00:00","Total":"71","PV":"71"},{"Time":"2023-08-29T09:00:00+00:00","Total":"85","PV":"85"},{"Time":"2023-08-29T10:00:00+00:00","Total":"95","PV":"95"},{"Time":"2023-08-29T11:00:00+00:00","Total":"98","PV":"98"},{"Time":"2023-08-29T12:00:00+00:00","Total":"98","PV":"98"},{"Time":"2023-08-29T13:00:00+00:00","Total":"98","PV":"98"},{"Time":"2023-08-29T14:00:00+00:00","Total":"88","PV":"88"},{"Time":"2023-08-29T15:00:00+00:00","Total":"65","PV":"65"},{"Time":"2023-08-29T16:00:00+00:00","Total":"39","PV":"39"},{"Time":"2023-08-29T17:00:00+00:00","Total":"15","PV":"15"},{"Time":"2023-08-29T18:00:00+00:00","Total":"3","PV":"3"},{"Time":"2023-08-29T18:07:07+00:00","Total":"0","PV":"0"}]`


Um das Problem zu reproduzieren, der Adapter "pvforecast" erstellt beispielsweise solche Datenpunkte. (Name des Datenpunktes = JSONTable).
Fügt man diesen Datenpunkt in das enum von hiob und möchte dann einen Sync in der App durchführen führt das zu einer Endlosschleife. Sobald der Datenpunkt wieder entfernt wird, geht alles wieder.

**Comment by moba15** [comment]
Vielen Dank für das Issue, ich werde es mir mal genauer anschauen woran das liegen könnte

**Comment by moba15** [comment]
Sollte mit dem neuen Adapter behoben worden sein!
